name: Nuget package publish when new release published for .NET

on:
  release:
    types: [published]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Replace tokens
    - uses: cschleiden/replace-tokens@v1.1
      with: 
        files: '["**/Secrets.cs"]' # optional, default is #{
      env:
        TOP_SECRET: ${{secrets.TOP_SECRET}}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}       
    - name: dotnet restore
      run: dotnet restore
    - name: dotnet build
      run: dotnet build -c Release --no-restore ./src/NugetWithGithubActions/NugetWithGithubActions.csproj
    - name: dotnet pack
      run: dotnet pack -c Release -o packages ./src/NugetWithGithubActions/NugetWithGithubActions.csproj
    - name: dotnet nuget push
      run: dotnet nuget push ./packages/*.nupkg --skip-duplicate

